project:
  type: website
  output-dir: docs
  
website:
  title: "Renee's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://reneezale.github.io/RZale-website/
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Renee Zale"

format:
  html:
    theme: cerulean
    toc: true

editor: source

